//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.19 at 03:10:14 PM MESZ 
//


package net.cloudfeeds.model;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="created-at" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="downloadable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="original-format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permalink-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artwork-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}user"/>
 *         &lt;element name="download-url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "createdAt",
    "duration",
    "description",
    "downloadable",
    "title",
    "originalFormat",
    "permalinkUrl",
    "artworkUrl",
    "user",
    "downloadUrl",
    "playbackCount"
})
@XmlRootElement(name = "track")
public class Track {

    @XmlElement(required = true)
    protected BigInteger id;
    

    @XmlElement(name = "created-at", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createdAt;
    @XmlElement(required = true)
    protected BigInteger duration;
    @XmlElement(required = true)
    protected String description;
	@XmlElement(required = true)
    protected boolean downloadable;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(name = "original-format", required = true)
    protected String originalFormat;

    @XmlElement(name = "permalink-url", required = true)
    protected String permalinkUrl;
    @XmlElement(name = "artwork-url", required = true)
    protected String artworkUrl;
    @XmlElement(required = true)
    protected User user;
    @XmlElement(name = "download-url")
    protected String downloadUrl;
    @XmlElement (name = "playback-count")
    protected BigInteger playbackCount;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedAt(XMLGregorianCalendar value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the downloadable property.
     * 
     */
    public boolean isDownloadable() {
        return downloadable;
    }

    /**
     * Sets the value of the downloadable property.
     * 
     */
    public void setDownloadable(boolean value) {
        this.downloadable = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the originalFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalFormat() {
        return originalFormat;
    }

    /**
     * Sets the value of the originalFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalFormat(String value) {
        this.originalFormat = value;
    }

    /**
     * Gets the value of the permalinkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermalinkUrl() {
        return permalinkUrl;
    }

    /**
     * Sets the value of the permalinkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermalinkUrl(String value) {
        this.permalinkUrl = value;
    }

    /**
     * Gets the value of the artworkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtworkUrl() {
        return artworkUrl;
    }

    /**
     * Sets the value of the artworkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtworkUrl(String value) {
        this.artworkUrl = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the downloadUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * Sets the value of the downloadUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDownloadUrl(String value) {
        this.downloadUrl = value;
    }

    /**
     * Gets the value of the playbackCount property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getPlaybackCount() {
        return playbackCount;
    }

    /**
     * Sets the value of the playbackCount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setPlaybackCount(BigInteger value) {
        this.playbackCount = value;
    }

}
